# Generated by Django 3.2.7 on 2021-09-27 05:08

from django.db import migrations, models
import django.db.models.deletion
import main.utils.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=128, unique=True)),
                ('course_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LabGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_group_name', models.CharField(max_length=64)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('matric', models.CharField(max_length=9, unique=True)),
                ('photo', main.utils.custom_fields.ContentTypeRestrictedFileField(blank=True, null=True, upload_to=main.utils.custom_fields.ContentTypeRestrictedFileField.update_student_photo_filename)),
                ('lab_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labgroup')),
            ],
        ),
        migrations.CreateModel(
            name='LabSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=64)),
                ('date_time_start', models.DateTimeField()),
                ('date_time_end', models.DateTimeField()),
                ('lab_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Late'), ('4', 'Absent with valid reason')], help_text='Attendance status', max_length=1)),
                ('date_time_captured', models.DateTimeField(null=True)),
                ('date_time_modified', models.DateTimeField(auto_now=True)),
                ('remarks', models.CharField(max_length=256)),
                ('lab_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.labsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
