# Generated by Django 3.2.7 on 2021-09-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_taken_with_facial_recognition',
            field=models.BooleanField(default=False, help_text='Check if this record is created with facial recognition module'),
        ),
    ]
