# Generated by Django 3.2.7 on 2021-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_attendancerecord_is_taken_with_facial_recognition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='date_time_captured',
            field=models.DateTimeField(help_text='Date Time of Attendance Capture', null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date_time_modified',
            field=models.DateTimeField(auto_now=True, help_text='Date Time Last Modified'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='remarks',
            field=models.CharField(help_text='Special Remarks (Eg. Late due to car breakdown)', max_length=256),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(help_text='Course Code (Eg. CZ3002)', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(help_text='Course Name (Eg. Software Engineering)', max_length=128),
        ),
        migrations.AlterField(
            model_name='labgroup',
            name='lab_group_name',
            field=models.CharField(help_text='Lab Group Name (Eg. FSP3)', max_length=64),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='session_name',
            field=models.CharField(help_text='Session Name (Eg. Lab 1, Lab 2)', max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric',
            field=models.CharField(help_text='Student Matric Number)', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Student Name)', max_length=64),
        ),
    ]
