# Generated by Django 3.2.7 on 2021-09-27 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210927_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabGroupStudentPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_group', models.ForeignKey(help_text='Lab Group', on_delete=django.db.models.deletion.CASCADE, to='main.labgroup')),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
