# Generated by Django 3.2.7 on 2021-09-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_labgroupstudentpair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lab_group',
        ),
    ]
