# Generated by Django 3.2.7 on 2021-09-28 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_student_photo'),
        ('main', '0005_remove_student_lab_group'),
    ]

    operations = [
    ]
