# Generated by Django 3.2.7 on 2021-09-28 05:47

from django.db import migrations, models
import django.db.models.deletion
import main.utils.custom_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_merge_20210928_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='lab_session',
            field=models.ForeignKey(help_text='Lab session id', on_delete=django.db.models.deletion.CASCADE, to='main.labsession'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='remarks',
            field=models.CharField(blank=True, help_text='Special Remarks (Eg. Late due to car breakdown)', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('1', 'Present'), ('2', 'Absent'), ('3', 'Late'), ('4', 'Absent with valid reason')], help_text='Attendance status. Available options: 1 - Present, 2 - Absent, 3 - Late, 4 - Absent with valid reason', max_length=1),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(help_text='Student id', on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterField(
            model_name='labgroup',
            name='course',
            field=models.ForeignKey(help_text='Course id', on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
        migrations.AlterField(
            model_name='labgroupstudentpair',
            name='lab_group',
            field=models.ForeignKey(help_text='Lab Group id', on_delete=django.db.models.deletion.CASCADE, to='main.labgroup'),
        ),
        migrations.AlterField(
            model_name='labgroupstudentpair',
            name='student',
            field=models.ForeignKey(help_text='Student id', on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
        migrations.AlterField(
            model_name='labsession',
            name='lab_group',
            field=models.ForeignKey(help_text='Lab group id', on_delete=django.db.models.deletion.CASCADE, to='main.labgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matric',
            field=models.CharField(help_text='Student Matric Number', max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Student Name', max_length=64),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=main.utils.custom_fields.ContentTypeRestrictedFileField(help_text='Photo of student, there must be exactly 1 face in the photo.', upload_to=main.utils.custom_fields.ContentTypeRestrictedFileField.update_student_photo_filename),
        ),
    ]
